/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyView;

import MyContorller.ActionController;
import MyContorller.TableActionListener;
import MyModel.HeaderInvoice;
import MyModel.HeaderInvoiceTable;
import MyModel.Item;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author amr
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
      //   controller = new ActionController(this);
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoiceTab1 = new javax.swing.JTable();
        Btn_SaveInvoice = new javax.swing.JButton();
        Btn_SaveInvoice.addActionListener(controller);
        Btn_DeleteInvoice = new javax.swing.JButton();
        Btn_DeleteInvoice.addActionListener(controller);
        NonEditLbl_InvoiceNo = new javax.swing.JLabel();
        NonEditLbl_InvoiceDate = new javax.swing.JLabel();
        NonEditLbl_CSTName = new javax.swing.JLabel();
        NonEditLbl_InvoiceTotal = new javax.swing.JLabel();
        Lbl_InvoiceDate = new javax.swing.JLabel();
        Lbl_InvoiceNo = new javax.swing.JLabel();
        Lbl_CSTName = new javax.swing.JLabel();
        Lbl_InvoiceTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemsTab2 = new javax.swing.JTable();
        Btn_NewItem = new javax.swing.JButton();
        Btn_NewItem.addActionListener(controller);
        Btn_DeleteItem = new javax.swing.JButton();
        Btn_DeleteItem.addActionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_Load = new javax.swing.JMenuItem();
        MenuItem_Load.addActionListener(controller);
        MenuItem_Save = new javax.swing.JMenuItem();
        MenuItem_Save.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoiceTab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvoiceTab1.getSelectionModel().addListSelectionListener(selectionListener);
        jScrollPane1.setViewportView(InvoiceTab1);

        Btn_SaveInvoice.setLabel("Save Invoice");
        Btn_SaveInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SaveInvoiceActionPerformed(evt);
            }
        });

        Btn_DeleteInvoice.setLabel("Delete Invoice");
        Btn_DeleteInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteInvoiceActionPerformed(evt);
            }
        });

        NonEditLbl_InvoiceNo.setText("Invoice No");

        NonEditLbl_InvoiceDate.setText("Date");

        NonEditLbl_CSTName.setText("Customer Name");

        NonEditLbl_InvoiceTotal.setText("Total");

        Lbl_InvoiceDate.setText(".");

        Lbl_InvoiceNo.setText(".");

        Lbl_CSTName.setText(".");

        Lbl_InvoiceTotal.setText(".");

        ItemsTab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(ItemsTab2);

        Btn_NewItem.setLabel("New Item");

        Btn_DeleteItem.setLabel("Delete Item");

        jMenu1.setText("File");

        MenuItem_Load.setText("Load");
        jMenu1.add(MenuItem_Load);

        MenuItem_Save.setText("save");
        jMenu1.add(MenuItem_Save);
        MenuItem_Save.getAccessibleContext().setAccessibleName("Save");

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NonEditLbl_InvoiceNo)
                                    .addComponent(NonEditLbl_InvoiceDate)
                                    .addComponent(NonEditLbl_CSTName)
                                    .addComponent(NonEditLbl_InvoiceTotal))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_InvoiceTotal)
                                    .addComponent(Lbl_CSTName)
                                    .addComponent(Lbl_InvoiceDate)
                                    .addComponent(Lbl_InvoiceNo)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Btn_SaveInvoice)
                        .addGap(81, 81, 81)
                        .addComponent(Btn_DeleteInvoice)
                        .addGap(155, 155, 155)
                        .addComponent(Btn_NewItem)
                        .addGap(105, 105, 105)
                        .addComponent(Btn_DeleteItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NonEditLbl_InvoiceNo)
                                .addGap(14, 14, 14)
                                .addComponent(NonEditLbl_InvoiceDate))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lbl_InvoiceNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lbl_InvoiceDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NonEditLbl_CSTName)
                            .addComponent(Lbl_CSTName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NonEditLbl_InvoiceTotal)
                            .addComponent(Lbl_InvoiceTotal))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_SaveInvoice)
                    .addComponent(Btn_DeleteInvoice)
                    .addComponent(Btn_NewItem)
                    .addComponent(Btn_DeleteItem))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SaveInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SaveInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_SaveInvoiceActionPerformed

    private void Btn_DeleteInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DeleteInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AppFrame().setVisible(true);
            }
          // frame.listener.LoadFiles("InvoiceHeader.csv","InvoiceLine.csv");
          
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_DeleteInvoice;
    private javax.swing.JButton Btn_DeleteItem;
    private javax.swing.JButton Btn_NewItem;
    private javax.swing.JButton Btn_SaveInvoice;
    private javax.swing.JTable InvoiceTab1;
    private javax.swing.JTable ItemsTab2;
    private javax.swing.JLabel Lbl_CSTName;
    private javax.swing.JLabel Lbl_InvoiceDate;
    private javax.swing.JLabel Lbl_InvoiceNo;
    private javax.swing.JLabel Lbl_InvoiceTotal;
    private javax.swing.JMenuItem MenuItem_Load;
    private javax.swing.JMenuItem MenuItem_Save;
    private javax.swing.JLabel NonEditLbl_CSTName;
    private javax.swing.JLabel NonEditLbl_InvoiceDate;
    private javax.swing.JLabel NonEditLbl_InvoiceNo;
    private javax.swing.JLabel NonEditLbl_InvoiceTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

  
private ActionController controller=new ActionController(this);
  private ArrayList<HeaderInvoice> invoicesArray;
    private ArrayList<Item> linesArray;
    private HeaderInvoiceTable headerTableModel;
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
    private TableActionListener selectionListener = new TableActionListener(this);

    public ArrayList<Item> getLinesArray() {
        return linesArray;
    }

    public void setLinesArray(ArrayList<Item> linesArray) {
        this.linesArray = linesArray;
    }
    
    public void setInvoicesArray(ArrayList<HeaderInvoice> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }

    public ArrayList<HeaderInvoice> getInvoicesArray() {
        return invoicesArray;
    }
    
    public HeaderInvoice getInvObject(int Num) {
        for (HeaderInvoice inv : invoicesArray) {
            if (inv.getHeader_No() == Num) {
                return inv;
            }
        }
        return null;
    }

    public HeaderInvoiceTable getHeaderTableModel() {
      return headerTableModel;
    }

    public void setHeaderTableModel(HeaderInvoiceTable headerTableModel) {
       this.headerTableModel = headerTableModel;
    }

    public JTable getInvHTbl() {
        return InvoiceTab1;
    }

    public JTable getInvLTbl() {
        return ItemsTab2;
    }

    public JLabel getCustNameLbl() {
        return Lbl_CSTName;
    }

    public JLabel getInvDateLbl() {
        return Lbl_InvoiceDate;
    }

    public JLabel getInvNumLbl() {
        return Lbl_InvoiceNo;
    }

    public JLabel getInvTotalIbl() {
        return Lbl_InvoiceTotal;
    }

    public ActionController getActionListener() {
        return controller;
    }
    
}
